### ISSUE TITLE
Increase visibility of this project

### ISSUE THREAD

**Issue by eterps** [frankroeder/parrot.nvim#12]
@frankroeder I'm really happy with parrot.nvim, I like that it is based on gp.nvim while allowing other providers as well.
I think it might be useful to let more users know that this project exists by announcing it at:

https://www.reddit.com/r/neovim/

r/neovim is a pretty active community and it will increase the visibility of this project.

Let me know what you think, I'd rather let you announce the project. But if you're actively avoiding Reddit let me know, I'd be happy to do it for you instead.

**Comment by eterps** [comment]
https://neovim.discourse.group/c/showcase/15 might be an option as well, but there's less activity compared to r/neovim

**Comment by frankroeder** [comment]
Thank you @eterps, I really appreciate your suggestion. Please feel free to proceed as you wish. I initially planned to announce the plugin across different platforms in the future, once I've improved the README a bit. 
However, I haven't yet found the time to do so.

**Comment by eterps** [comment]
Moderator approval took a while, but here it is on Reddit (could use some upvotes though):

https://www.reddit.com/r/neovim/comments/1dhy589/parrotnvim_use_claude_opus_ollama_perplexityai/

**Comment by eterps** [comment]
On Lemmy:

- https://sopuli.xyz/post/13925443
- https://programming.dev/post/15675507

**Comment by eterps** [comment]
Now on neovim discourse as well:

https://neovim.discourse.group/t/parrot-nvim-use-claude-opus-ollama-perplexity-ai-and-openai-from-neovim/4964

I noticed Lemmy users are strongly biased against anything involving LLMs.

I'm closing this issue for now. Feel free to reopen it in case of major updates and I will repeat posting (except for Lemmy).
