### ISSUE TITLE
Add PrtChatPaste support

### ISSUE THREAD

**Issue by quolpr** [frankroeder/parrot.nvim#14]
Hi! Migration from gp.nvim, and I use PrtChatPaste a lot. Could parrot implement this?

**Comment by frankroeder** [comment]
Hi @quolpr, I removed ChatPaste because you can do the same thing by simple calling `PrtChatToggle` or `PrtChatNew`. Or am I missing something?

**Comment by quolpr** [comment]
@frankroeder the usecase is such:
1. I open new chat in popup. Chat there
2. Then realize that I need to add more context to chat, so I close it.
3. Find needed code, visualise it, paste with PrtChatPaste to the current chat

So, I don't need to yank the visualise, it's just directly go to chat

**Comment by frankroeder** [comment]
Sorry @quolpr, I overlook that particular use-case. However, it is back with commit 20232e3292577b93168f5c781c0bd021e4bcc3bc on main.
