### ISSUE TITLE
PrtChatRespond results in ".... does not look like a chat file"

### ISSUE THREAD

**Issue by RobertBrunhage** [frankroeder/parrot.nvim#32]
I've gone through the configuration and is using the following config.

```lua
	{
		"frankroeder/parrot.nvim",
		tag = "v0.3.7",
		dependencies = { "ibhagwan/fzf-lua", "nvim-lua/plenary.nvim" },
		-- optionally include "rcarriga/nvim-notify" for beautiful notifications
		config = function()
			require("parrot").setup({
				providers = {
					anthropic = {
						api_key = os.getenv "ANTHROPIC_API_KEY",
					},
				},
			})
		end,
	},

```

The chat file is named `~/.local/share/nvim/parrot/chats/2024-07-26.14-53-45.300.md`, and opened through `:PrtChatNew` and tried to respond with `:PrtChatRespond`.

Am I missing something in the config?

**Comment by frankroeder** [comment]
Hi @RobertBrunhage, can you share the head of your chat file. There are basically 3 things that must hold according to https://github.com/frankroeder/parrot.nvim/blob/670e5d6768690620fe9d7bd0959228c89b4f0dda/lua/parrot/utils.lua#L257 for parrot.nvim to recognize the file as chat. Have you deleted the first lines of the initial chat file?

**Comment by RobertBrunhage** [comment]
@frankroeder here is the entire chat file

```
# topic: ?

---

🗨:

I have the following content from /Users/robertbrunhage/personal/projects/.dotfiles/nvim/.config/nvim/lua/plugins.lua:

```lua
	{
		"frankroeder/parrot.nvim",
		tag = "v0.3.7",
		dependencies = { "ibhagwan/fzf-lua", "nvim-lua/plenary.nvim" },
		-- optionally include "rcarriga/nvim-notify" for beautiful notifications
		config = function()
			require("parrot").setup({
				providers = {
					anthropic = {
						api_key = "api keeeeey :)",
					},
				},
			})
		end,
	},
```


How does this look?
```

**Comment by frankroeder** [comment]
@RobertBrunhage, I have tested this with a minimal Neovim setup, with only lazy.nvim and parrot.nvim installed. As expected, there are no issues regarding the chat file detection. Therefore, I am unable to reproduce your case. Feel free to try it yourself (https://lazy.folke.io/installation).

Let me know if you have further hints!

**Comment by RobertBrunhage** [comment]
Going to debug a bit more but I would like to say I have quite a lean neovim config setup https://github.com/RobertBrunhage/nvim/tree/main

**Comment by frankroeder** [comment]
I was also thinking about something like a symlink. It’s great that you found the error! I apologize for not considering your PR. I had to add the same check for the other config directory too (see https://github.com/frankroeder/parrot.nvim/commit/91bbf78c6bda02cd73bc7ab7c512269e54). Furthermore, I believe it is cleaner to handle this in the main code rather than inside the config.

**Comment by RobertBrunhage** [comment]
> I was also thinking about something like a symlink. It’s great that you found the error! I apologize for not considering your PR. I had to add the same check for the other config directory too (see [91bbf78](https://github.com/frankroeder/parrot.nvim/commit/91bbf78c6bda02cd73bc7ab7c512269e54)). Furthermore, I believe it is cleaner to handle this in the main code rather than inside the config.

No worries at all! Thanks for the quick response and implementing a fix!

**Comment by RobertBrunhage** [comment]
@frankroeder I just started using the latest tag instead of my fork and I still get the issue, but only in repos that is not my neovim repo.

```
file_name: /Users/robertbrunhage/personal/projects/.dotfiles/bin/.local/share/nvim/parrot/chats/2024-07-30.07-17-08.673.md
chat_dir: /Users/robertbrunhage/.local/share/nvim/parrot/chats
File name does not start with chat_dir
```

**Comment by frankroeder** [comment]
Okay, maybe I'm still misunderstanding your setup — sorry! I just tested it with the "chat" folder being a symlink, and I didn't encounter any issues. What do you mean by "that are not your repo"? Are you testing out other dotfiles?

Hmm, why does it end up in the `bin/` folder?

Instead of using your fork, you could simply add this to your Parrot config:
```lua
chat_dir = vim.loop.fs_realpath(vim.fn.stdpath("data"):gsub("/$", "") .. "/parrot/chats"
```

Thanks for reporting!

**Comment by RobertBrunhage** [comment]
> Okay, maybe I'm still misunderstanding your setup — sorry! I just tested it with the "chat" folder being a symlink, and I didn't encounter any issues. What do you mean by "that are not your repo"? Are you testing out other dotfiles?

It works when I am testing chat in my dotfiles where neovim is setup

When I am opening another location (such as another project), it does not.

> Instead of using your fork, you could simply add this to your Parrot config:
> 
> `chat_dir = vim.loop.fs_realpath(vim.fn.stdpath("data"):gsub("/$", "") .. "/parrot/chats")`
> Thanks for reporting!

Using this works without the fork!
