### ISSUE TITLE
Just a thought

### ISSUE THREAD

**Issue by Robitx** [frankroeder/parrot.nvim#38]
Hey Frank,
about a month ago I've got back to the active development of Gp.nvim - multi provider branch got merged, code base got split and cleaned up, whisper and imager are now in modules which can be completely disabled with single config option, etc.

So when I got around to "exploring the state of the competition" I thought it's a shame there are several projects converging on very similar target. On one hand yes, competition is good yadda yadda yadda, on the other hand instead of collaborating and getting to the target faster, we're fragmenting the user base and wasting available man power (since any meaningful improvement will be sooner than later absorbed by "competing projects").

If you have significant emotional attachment the the Parrot and it's a kid project you're unwilling to leave behind, then it's fine by me and by all means go ahead.

If you don't have any significant emotional attachment to it and your goal is to have AI integration Neovim users (including two of us) deserve and are satisfied with - did you notice any philosophical/design differences which would make collaboration impossible? If not, I'd give you maintainer access to Gp without blink of an eye.

Tibor

PS: There is a [Gp's Discord](https://discord.com/invite/dYyHmyNpv7) in case you would want to talk in real time.

**Comment by frankroeder** [comment]
Hello Tibor,

Thank you for reaching out and offering the opportunity to collaborate on gp.nvim.

I have been closely following your development and noticed that your involvement with gp.nvim was revived about a month ago, around the same time I started working on this fork. It's great to see that!

I also noted your comment about fragmentation when you introduced your Discord channel and had anticipated that it might be related to this project.

For now, I will continue working on Parrot, as it provides me with numerous opportunities to test out ideas specifically related to integrating LLMs with Neovim. Additionally, I have learned a lot from working on this project, and this experience is invaluable for maintaining such a plugin, especially if I become a contributor to gp.nvim.

If both projects eventually converge towards the same set of features, it would definitely make sense to join forces. I will reach out to you on Discord.
