### ISSUE TITLE
docs and implementation don't match on user_input_ui = "buffer"

### ISSUE THREAD

**Issue by dlants** [frankroeder/parrot.nvim#44]
The [docs](https://github.com/frankroeder/parrot.nvim/blob/3f74c06743ccbe200067892022fd84b908f3bce5/README.md?plain=1#L257) suggest that you should be able to use "buffer" as a user_input_ui option.

However, the actual [code](https://github.com/frankroeder/parrot.nvim/blob/3f74c06743ccbe200067892022fd84b908f3bce5/lua/parrot/chat_handler.lua#L1318) doesn't support this option, and instead errors with:
```
Invalid user input ui option: buffer
```

**Comment by frankroeder** [comment]
Hey @dlants, thanks for pointing out this bug. It has been fixed with commit [22abeb3](https://github.com/frankroeder/parrot.nvim/commit/22abeb3378b6c978a8fd7629a755e1af44d3f40c) and will be included in the next release!
