### ISSUE TITLE
Breach of MIT Licence

### ISSUE THREAD

**Issue by Robitx** [frankroeder/parrot.nvim#47]
Note that I've made backup fork of parrot.nvim for evidence.

![image](https://github.com/user-attachments/assets/a17d6faa-8253-49ee-aeb9-0dc6583a9b7c)

I was willing to let this pass, since you've at least referenced the gp.nvim at the top of the readme.

But since you're slowly removing traces to the original active project (from which all the main features of the parrot comes from) and promoting it as yours (logo, funding, keywords for people to find it, releases) instead of contributing to the original.

![image](https://github.com/user-attachments/assets/f9f6e968-fd40-4dfd-9e1a-190f5b0efeef)

Is this what you want your name to be associated with? Where every future employer can look up licence violations and copyright infringement? Fine by me.

**Comment by frankroeder** [comment]
Please have a look at the end of the file.
