### ISSUE TITLE
Can't get openai and perplexity models to show up

### ISSUE THREAD

**Issue by IroncladDev** [frankroeder/parrot.nvim#48]
I'm using the Lazy package manager.

I tried the config in https://github.com/frankroeder/parrot.nvim/issues/3

When I run `:PrtModel`, I should see the openai and perplexity models. I only see Ollama models. This is my config:

```lua
return {
	"frankroeder/parrot.nvim",
	dependencies = { "ibhagwan/fzf-lua", "nvim-lua/plenary.nvim", "rcarriga/nvim-notify" },
	cond = os.getenv("OPENAI_API_KEY") ~= nil and os.getenv("PERPLEXITY_API_KEY") ~= nil,
	config = function()
		require("parrot").setup({
			providers = {
				pplx = {
					api_key = os.getenv("PERPLEXITY_API_KEY"),
				},
				openai = {
					api_key = os.getenv("OPENAI_API_KEY"),
				},
				ollama = {},
			},
			chat_conceal_model_params = false,
		})
	end,
}

```

I tried to find any issues regarding this and look around. I couldn't find anything.

**Comment by IroncladDev** [comment]
Nevermind, :PrtProvider works.

Sorry about that.

**Comment by frankroeder** [comment]
Dear @IroncladDev,

Thank you for reporting this issue. First, you need to remove the configuration option `chat_conceal_model_params` as it is not a valid choice for this fork. To select the OpenAI or Perplexity models, you need to execute `PrtProvider` first. You can verify your selection with `PrtStatus`. Only then will you be able to select the correct models.

**Comment by frankroeder** [comment]
Great, alright!
