### ISSUE TITLE
PrtAsk is always the same answer

### ISSUE THREAD

**Issue by chrishrb** [frankroeder/parrot.nvim#57]
First of all: Thanks for this amazing plugin 👍 

I have a problem with PrtAsk. If I ask the first question, the answer is as expected, but If i ask a completely different question directly afterwards, the answer is in context to the first question and not to the second. I use Ollama locally.

Example:
PrtAsk -> What is 2+2 -> Answer: 2 + 2 = 4
After closing with ESC and again asking:
PrtAsk -> What is 4+4 -> Answer: The answer is 4. 2 + 2 = 4.

**Comment by frankroeder** [comment]
Dear @chrishrb,
First of all, thank you very much. It's great to hear that you are enjoying it so far. You have indeed identified a strange behavior that I was able to replicate. Upon enabling debug logging, I discovered that it uses the same user prompt—in your case, 2+2—twice. I will have a look at it.

**Comment by frankroeder** [comment]
Fixed with commit [0db1e3beff0c434fec13c809bd105a4485946ece](https://github.com/frankroeder/parrot.nvim/commit/0db1e3beff0c434fec13c809bd105a4485946ece). Thank you!
