### ISSUE TITLE
PrtChatNew toggle_target not working as expected

### ISSUE THREAD

**Issue by chrishrb** [frankroeder/parrot.nvim#59]
So I have another problem now, which I think is also very fast to fix: If you create a new chat with `PrtChatNew` and the toggle_target is set to vsplit, a new buffer is created instead of showing it as a vsplit. For `PrtChatToggle` this works as expected.

**Comment by frankroeder** [comment]
Fixed with commit [345fb4e3bed17c1822c1cd40ccec158be13d3f7e](https://github.com/frankroeder/parrot.nvim/commit/345fb4e3bed17c1822c1cd40ccec158be13d3f7e). Let me know if it works as expected. I definitely need to rethink this workflow at some point.
