### ISSUE TITLE
PrtProvider and PrtAgent doesn't accept args, always run fzf

### ISSUE THREAD

**Issue by lzieniew** [frankroeder/parrot.nvim#6]
After updating to the last version of parrot.nvim, I've encountered an error with PrtProvied and PrtAgent. I've defined custom shortcuts that were relying on both of those commands to accept parameters, but after the update the shortcuts stopped working. I've run the commands manually, and even when I did it like :PrtProvider openai it opened fzf window where I had to select provied, as if the "openai" argument was ignored. The same problem was with PrtAgent.

I've prepared simple fix for this on my fork: https://github.com/lzieniew/parrot.nvim and it works for my purposes. 
If you are interested in merging it I can open a Pull request - but it's a quick fix and a bit messy, so you might want to rework it

**Comment by frankroeder** [comment]
Hello @lzieniew, thank you very much for your valuable feedback.

Which version/commit are you currently using?

Notwithstanding the above, in the latest commit, I have added the option to pass an argument to `PrtProvider` and `PrtAgent`, even if fzf-lua is installed. I hope this helps and you can continue enjoying the plugin.

**Comment by lzieniew** [comment]
Previously I've encountered the problem on 4f99c0, but now on the newest version of plugin it works, thanks

Btw, great plugin, thanks for developing and publishing it :)
