### ISSUE TITLE
README example doesn't work

### ISSUE THREAD

**Issue by Dioprz** [frankroeder/parrot.nvim#60]
Hi Frank,

I was trying to create some hooks starting from a README example. I started with this one (as I needed a similar operation).

https://github.com/frankroeder/parrot.nvim/blob/0db1e3beff0c434fec13c809bd105a4485946ece/README.md?plain=1#L463-L489

Trying to execute this hook fails. However, when I evaluate the `get_model` call with "command" as an argument, everything works as expected. Is this correct? Should it work without it?

I also want to report that, even with the hook being well defined, the first time I open any file and select a text to apply my hook, it shows a message saying: `Error E20: Mark not set`. I need to Escape the selection, select again, and then it works. Happens with `PrtImplement` too.

Finally, I would like to understand what differences are between the "command" and "chat" parameters. If you have some time to document it, it would be much appreciated!

As always, thank you very much for all your good work man.

**Comment by frankroeder** [comment]
Dear @Dioprz,

I did indeed made a mistake with that hook example. I have fixed it in the latest commit. Yes, adding `"command"` is correct and was the missing piece.

Thank you for reporting this issue. I will look into it shortly. Can you tell me which version/commit of parrot you are using, your OS, and the version of Neovim?

The documentation still needs some improvements and is not yet complete, so thank you for your suggestion. I have already taken several steps to remove the concept of agents and to actually make the `command` and `chat` routines more similar. Currently, the only differences are the system prompts and a slot in the state to store the last model selection.

**Comment by Dioprz** [comment]
Sorry for the missing details in the second report.  I've discovered that it was an error related to how I declared the keys, not with Parrot itself:

```lua
    {
      '<leader>aio',
      -- "<cmd><,'>PrtCommand<cr> Error
      ":'<,'>PrtCommand<cr>",  -- Fix
      desc = 'Parrot AI google docstring migration from selection',
      mode = { 'v' },
    },
```

Thanks for the fix in documentation and the quick response! That's all for this issue 👍🏻
