### ISSUE TITLE
Using any of the Perplexity models results in tons of buffer and curl errors

### ISSUE THREAD

**Issue by IroncladDev** [frankroeder/parrot.nvim#61]
Whenever I use any of the perplexity models, it seems to stream properly, but then I get a series of curl errors and buffer errors to the point where it's almost unusable.

OpenAI models are working perfectly fine as expected.

- Operating Sytem: MacOS
- Package Manager for Nvim: Lazy

Screen Recording:
https://github.com/user-attachments/assets/859b47e3-a3f3-4066-95d6-1d7bb042d2a4

**Comment by frankroeder** [comment]
Hi @IroncladDev ,
Thank you for your screen recording. I currently do not have a Perplexity subscription or API credit. Let me find a way to get access so I can debug this error.

**Comment by IroncladDev** [comment]
Fixed in a single day.

You're a machine, frank.

Thank you so much.
