### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by aftab0094** [frankroeder/parrot.nvim#65]
I have windows 10 machine up to date neovim(NvChad) config, but after installation the command line arguments don't appear...

**Comment by frankroeder** [comment]
Dear @aftab0094, I apologize, but I currently cannot guarantee flawless Windows support. Have you considered using WSL?

**Comment by aftab0094** [comment]
I have tried it on Google cloud console and got the same issue

**Comment by frankroeder** [comment]
Please share your config/setup for `parrot.nvim`.

**Comment by aftab0094** [comment]
config
```
{
  "frankroeder/parrot.nvim",
  dependencies = { "ibhagwan/fzf-lua", "nvim-lua/plenary.nvim" },
  opts = {}
}
```

the same config on lazyVim and got notified this error:
```
Failed to run `config` for parrot.nvim

...ta/Local/nvim-data/lazy/parrot.nvim/lua/parrot/utils.lua:339: attempt to index local 'table' (a nil value)

# stacktrace:
  - parrot.nvim\lua\parrot\utils.lua:339 _in_ **has_valid_key**
  - parrot.nvim\lua\parrot\config.lua:318 _in_ **setup**
  - parrot.nvim\lua\parrot\init.lua:8 _in_ **setup**
  - lua/config/lazy.lua:17
  - init.lua:2
```

**Comment by frankroeder** [comment]
Dear @aftab0094, as mentioned in the README, you need to configure the providers you wish to use, such as OpenAI, Anthropic, or Ollama.

Have a look at the [setup](https://github.com/frankroeder/parrot.nvim?tab=readme-ov-file#setup) section.

**Comment by aftab0094** [comment]
edited config
```
return {
  "frankroeder/parrot.nvim",
  dependencies = { 'ibhagwan/fzf-lua', 'nvim-lua/plenary.nvim' },
  -- optionally include "rcarriga/nvim-notify" for beautiful notifications
  config = function()
    require("parrot").setup {
      -- Providers must be explicitly added to make them available.
      providers = {
        gemini = {
          api_key = os.getenv "GEMINI_API_KEY",
        },
      },
    }
  end,
}

```

it worked in lazyvim but when i tried nvchad it didn't.

later in nvchad when i added `event = "VeryLazy"` it loaded and worked, there were other plugins i had that had kind of the same problem

Thanks @frankroeder

**Comment by frankroeder** [comment]
Thank you @aftab0094, for tracking down this issue. It should be helpful for other NVChad users as well.
