### ISSUE TITLE
[suggestion] PrtRetry, but allow me to optionally change the prompt slightly

### ISSUE THREAD

**Issue by CrustyCode** [frankroeder/parrot.nvim#74]
I had a go at implementing it, but gave up trying to get the previous prompt into the popup window.

**Comment by CrustyCode** [comment]
Perhaps this is also possible with just a hook? Not sure

**Comment by frankroeder** [comment]
Hi @CrustyCode, this is definitely doable. I would suggest adding a new hook for that, maybe something like `PrtEdit`...

**Comment by frankroeder** [comment]
Hi @CrustyCode, feel free to check out the new feature on the [feat/prtedit](https://github.com/frankroeder/parrot.nvim/tree/feat/prtedit) branch. I would appreciate your feedback!

**Comment by frankroeder** [comment]
You are right, currently, `PrtRetry` and `PrtEdit` only support `PrtAppend`, `PrtPrepend`, and `PrtRewrite`.

**Comment by frankroeder** [comment]
> You are right, currently, `PrtRetry` and `PrtEdit` only support `PrtAppend`, `PrtPrepend`, and `PrtRewrite`.

For now, I stay with the edit support for the mentioned commands only. This has now been merged with #77.
