### ISSUE TITLE
Issue with Gemini and Config

### ISSUE THREAD

**Issue by LinkUpGames** [frankroeder/parrot.nvim#79]
When I try to use Gemini and send a basic prompt over, I am met with a 400 error response. My setup used to work around 2 weeks ago and it hasn't been changed since. I don't know if this is an error on Gemini's side or if my config is not sending the requests properly:

![image](https://github.com/user-attachments/assets/3cf082b2-34f8-4170-913f-5888a2813f33)
![image](https://github.com/user-attachments/assets/5afecca6-f3f7-432f-9d8e-b2c2e1a74937)

Config: 

```lua
{
    "frankroeder/parrot.nvim",
    dependencies = { "nvim-lua/plenary.nvim" },
    event = "VeryLazy",
    cond = os.getenv("GEMINI_API_KEY") ~= nil,
    opts = {
      style_popup_border = "rounded",
      chat_user_prefix = "💬:",
      llm_prefix = "🤖:",
      chat_free_cursor = true,
      toggle_target = "popup",
      online_model_selection = true,
      chat_shortcut_respond = { modes = { "n", "i" }, shortcut = "<CR>" },
      chat_shortcut_delete = { modes = { "n" }, shortcut = "<leader>ad" },
      chat_confirm_delete = false,
      providers = {
        gemini = {
          api_key = os.getenv("GEMINI_API_KEY"),
          topic_prompt = "You are helping me with my codebase",
          topic = {
            model = "gemini-1.5-flash",
          },
        },
      },
    },
    keys = {
      { "<leader>aj", "<CMD>PrtChatToggle popup<CR>", mode = { "n" }, desc = "Toggle AI Chat" },
      { "<leader>ak", "<CMD>PrtChatNew popup<CR>", mode = { "n" }, desc = "Open new AI Chat" },
      {
        "<leader>aj",
        ":'<,'>PrtChatPaste popup<CR>",
        mode = { "x" },
        desc = "Paste the selected into the latest AI Chat",
      },
    },
  }
```

**Comment by frankroeder** [comment]
Dear @LinkUpGames,

I was unable to reproduce the error you encountered. Everything appears to work fine on my end. To investigate the issue further, could you please start Neovim with `DEBUG_PARROT=1`? You can do this by running the command:
```bash
DEBUG_PARROT=1 nvim
```
Once Neovim is open, simply run `:PrtChatNew` and test your example again. After that, run `:PrtLog` to inspect the debug logs, which should provide more information on why the API call is failing. Please ensure you review the logs carefully for any sensitive information, such as credentials, before sharing them.

**Comment by LinkUpGames** [comment]
Hey! 

Thank you for your response. I removed the `parrot` folder under `.local/share/nvim/` and ran the same command again and managed to get a response. I don't know what could have caused the issue. I think it is safe to close the issue.
