### ISSUE TITLE
[feature]: Able to add custom models in config

### ISSUE THREAD

**Issue by alr86** [frankroeder/parrot.nvim#81]
I want to use OpenRouter in parrot, I can add its endpoint as OpenAI, but I can't add custom model to use it.
If already I can please add about it in README

**Comment by frankroeder** [comment]
Dear @alr86, this is a great idea. I have added the ability to include custom models in the branch referenced in PR #82. Please feel free to test it and share any feedback or report any issues you encounter.

**Comment by alr86** [comment]
Thanks for the quick help!  It works perfectly! 👍

**Comment by frankroeder** [comment]
Dear @alr86, I couldn't reproduce this issue as the default model is selected from the models defined for the provider. However, after that, there are no issues remembering the selection, right?

**Comment by alr86** [comment]
No, I've been using it since then without any issues👍
